name: release-wip

on:
  workflow_dispatch:
    inputs:
      increment:
        description: "SemVer Increment"
        required: true
        default: "prerelease"
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major
      releaseType:
        description: "Release type"
        required: true
        type: choice
        options:
          - latest
          - canary
      dryRun:
        description: "Dry Run (Skip branch/PR and release)"
        required: true
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      release-tag: ${{ steps.version.outputs.release-tag }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: install
        run: pnpm install --frozen-lockfile

      - name: version
        id: version
        run: |
          node scripts/compute-version.js "${{ inputs.increment }}" "${{ inputs.releaseType }}"
          VERSION=$(cat version | head -n 1)
          RELEASE_TAG=$(cat version | tail -n 1)
          echo "   DEBUG: version = $VERSION"
          echo "   DEBUG: release-tag = $RELEASE_TAG"

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "releaseTag=$RELEASE_TAG" >> "$GITHUB_OUTPUT"

      - name: bump version
        run: |
          ./scripts/bump-version.sh "${{ steps.version.outputs.version }}"

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --tag ${{ steps.version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        if: ${{ !inputs.dryRun }}
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "release: bump version to ${{ steps.version.outputs.version }}"
          title: "release: v${{ steps.version.outputs.version }}"
          body-path: ./CHANGELOG.md
          base: main
          branch: release/v${{ steps.version.outputs.version }}

  build-app:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build app
        run: pnpm --filter app build

      - name: upload app build
        uses: actions/upload-artifact@v7
        with:
          name: app-dist
          path: packages/app/dist/

  build-rust:
    needs: [bump-version, build-app]
    strategy:
      matrix:
        settings:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    runs-on: ${{ matrix.settings.os }}

    steps:
      - name: Checkout (Release)
        if: ${{ !inputs.dryRun }}
        uses: actions/checkout@v6
        with:
          ref: release/v${{ needs.bump-version.outputs.version }}

      - name: Checkout (Dry Run)
        if: ${{ inputs.dryRun }}
        uses: actions/checkout@v6

      - name: Download app artifact
        uses: actions/download-artifact@v7
        with:
          name: app-dist
          path: packages/app/dist/

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.96.0
          targets: ${{ matrix.settings.target }}

      - name: Build rust
        run: cargo build --target ${{ matrix.settings.target }} -p trek --release

      - name: Binary rename
        run: |
          mv target/${{ matrix.settings.target }}/release/trek${{ matrix.settings.ext }} target/${{ matrix.settings.target }}/release/trek-${{ matrix.settings.target }}${{ matrix.settings.ext }}

      - name: copy binary to dist folder
        run: |
          mkdir -p ./dist
          cp target/${{ matrix.settings.target }}/release/trek-${{ matrix.settings.target }}${{ matrix.settings.ext }} ./dist/trek-${{ matrix.settings.target }}${{ matrix.settings.ext }}

      - name: upload trek-cli
        uses: actions/upload-artifact@v7
        with:
          name: trek-${{ matrix.settings.target }}
          path: dist/trek-${{ matrix.settings.target }}${{ matrix.settings.ext }}

  release:
    needs: [build-rust, bump-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Release)
        if: ${{ !inputs.dryRun }}
        uses: actions/checkout@v6
        with:
          ref: release/v${{ needs.bump-version.outputs.version }}
          fetch-tags: true
          fetch-depth: 0

      - name: Checkout (Dry Run)
        if: ${{ inputs.dryRun }}
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./dist

      - name: compress binaries for each platform
        run: ./scripts/prepare-tarball.sh

      - name: generate SHASUMS.txt
        run: ./scripts/generate-checksums.sh

      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --unreleased --tag ${{ needs.bump-version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: release
        if: ${{ !inputs.dryRun }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.bump-version.outputs.version }}
          name: Trek CLI v${{ needs.bump-version.outputs.version }}
          draft: false
          body_path: ./CHANGELOG.md
          prerelease: ${{ inputs.releaseType == 'canary'}}
          files: |
            ./release/*
