name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check for File Changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - 'Cargo.toml'
              - '.github/workflows/test.yml'

  test:
    needs: check
    if: needs.check.outputs.rust == 'true'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.96.0
          targets: wasm32-unknown-unknown
          components: rustfmt

      - name: Cache cargo
        uses: swatinem/rust-cache@v2

      - name: cargo test
        run: |
          cargo test --workspace --all-targets
